name: Hello World Workflow

on:
  push:
    branches: [ develop ] # Solo se ejecuta cuando hay push a la rama 'develop'

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "¡Hola, GitHub Actions!"   